{% set name = "leg2cheb" %}
{% set version = "1.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/spectralDNS/Legendre-to-Chebyshev/archive/{{ version }}.tar.gz
  sha256: ccec28b94a8559db5bafcf0fb58e2095a7ab8c6b58f88be2d6a74eda60f73851

build:
  number: 1
  skip: true  # [win]
  script: 
    - cd src
    - meson setup build ${MESON_ARGS} || (cat $SRC_DIR/src/build/meson-logs/meson-log.txt; exit 1)
    - meson compile -C build
    - meson install -C build

requirements:
  build:
    - numpy >=2.0                        # [build_platform != target_platform] 
    - meson                              # [build_platform != target_platform]
    - python                             # [build_platform != target_platform]
    - cython                             # [build_platform != target_platform]
    - fftw                               # [build_platform != target_platform]
    - openblas                           # [build_platform != target_platform]
    - libopenblas =*=*openmp*            # [build_platform != target_platform]
    - ninja 
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp      # [linux]            
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }} 
    - {{ stdlib('c') }}

  host:
    - numpy >=2.0
    - meson                               
    - python
    - cython
    - fftw
    - openblas
    - libopenblas =*=*openmp*

  run:
    - python
    - fftw
    - openblas
    - libopenblas =*=*openmp*

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - l2c

about:
  home: https://github.com/spectralDNS/Legendre-to-Chebyshev
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Fast multipole Legendre/Chebyshev transforms

extra:
  recipe-maintainers:
    - mikaem
