{% set name = "leg2cheb" %}
{% set version = "1.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/spectralDNS/Legendre-to-Chebyshev/archive/{{ version }}.tar.gz
  sha256: 3ff70cecdb98cb851dc8b04709c616cdd6b3b681dee83c0c8b022a6422718189

build:
  number: 0
  skip: true  # [win]
  script: 
    - cd src
    - meson setup build ${MESON_ARGS} || (cat $SRC_DIR/src/build/meson-logs/meson-log.txt; exit 1)
    - meson compile -C build
    - meson install -C build

requirements:
  build:
    - ninja                               
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp      # [linux]            
    - {{ compiler('c') }}
    - {{ compiler('cxx') }} 
    - {{ stdlib('c') }}

  host:
    - numpy >=2.0
    - meson                               
    - python
    - cython
    - fftw
    - openblas
    - libopenblas =*=*openmp*
  run:
    - python
    - fftw
    - openblas
    - libopenblas =*=*openmp*

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - l2c

about:
  home: https://github.com/spectralDNS/Legendre-to-Chebyshev
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Fast multipole Legendre/Chebyshev transforms

extra:
  recipe-maintainers:
    - mikaem
